

services:
  frontend:
    build:
      context: ./invoice
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Maps port 80 on the host to port 80 in the frontend container
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Maps port 8081 on the host to port 8081 in the backend container
    restart: always
    environment:
      - NODE_ENV=production
